# Railway Configuration for DataCrypt Labs v3.1
# Auto-deploy optimized admin panel system

[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
# Production environment variables
RAILWAY_ENVIRONMENT = "production"
PORT = "${PORT}"
HOST = "0.0.0.0"

# Admin credentials (change in production)
ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "datacrypt2025"

# FastAPI settings
FASTAPI_ENV = "production"
DEBUG = "false"